### ISSUE TITLE
http://mehulkar.com/github-hall-of-fame/ => 404

### ISSUE THREAD

**Issue by alrra** [mehulkar/github-hall-of-fame#28]
![](https://cloud.githubusercontent.com/assets/1223565/5784245/14fbb484-9dd3-11e4-82c9-35d089d6780e.png)
## 

http://mehulkar.com/github-hall-of-fame/ result in a `404`

``` bash
$ curl -sSIL http://mehulkar.com/github-hall-of-fame/

HTTP/1.1 404 Not Found
Server: GitHub.com
Content-Type: text/html; charset=utf-8
ETag: "548922a8-23c3"
Content-Length: 9155
Accept-Ranges: bytes
Date: Fri, 16 Jan 2015 20:31:15 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-fra1226-FRA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1421440275.472738,VS0,VE89
Vary: Accept-Encoding
```

**Comment by mehulkar** [comment]
oh no!

my personal website gh-pages story is the problem. I switched from jekyll to middleman and broke the build. This project should have its own domain though. I'll set it up this weekend!

**Comment by mehulkar** [comment]
Fixed this for now: http://www.mehulkar.com/github-hall-of-fame/

Still need to setup custom domain.
