### ISSUE TITLE
Shadowsocks: Deleted, because of police

### ISSUE THREAD

**Issue by andygrunwald** [mehulkar/github-hall-of-fame#32]
https://github.com/shadowsocks/shadowsocks-iOS/issues/124#issuecomment-133630294

Sadly, the comment itself was edited :(
But maybe worth to add.

**Comment by vendethiel** [comment]
there's a mirror to the comment a bit later down

**Comment by herzmut** [comment]
What they said:
"Two days ago the police came to me and wanted me to stop working on this. Today they asked me to delete all the code from GitHub. I have no choice but to obey.
I hope one day I'll live in a country where I have freedom to write any code I like without fearing."

Solidarity fork (one of many):
https://github.com/dguhl/shadowsocks-iOS

https://github.com/dguhl/shadowsocks.git
https://github.com/dguhl/shadowsocks-windows.git
https://github.com/dguhl/shadowsocks-android.git
https://github.com/dguhl/shadowsocks-libev.git
https://github.com/dguhl/shadowsocks-gui.git
https://github.com/dguhl/openwrt-shadowsocks.git
https://github.com/dguhl/ChinaDNS.git
https://github.com/dguhl/shadowsocks-chromeapp.git

**Comment by jomo** [comment]
Full quote:

> Two days ago the police came to me and wanted me to stop working on this. Today they asked me to delete all the code from GitHub. I have no choice but to obey.
> 
> I hope one day I'll live in a country where I have freedom to write any code I like without fearing.
> 
> I believe you guys will make great stuff with Network Extensions.
> 
> Cheers!

**Comment by m0ls** [comment]
Latest save on **web.archive.org**: https://web.archive.org/web/20150822223925/https://github.com/shadowsocks/shadowsocks-iOS/issues/124

**Comment by zenyr** [comment]
Deeper perma mirror link

> https://web.archive.org/web/20150822223925/https://github.com/shadowsocks/shadowsocks-iOS/issues/124#issuecomment-133630294

**Comment by herzmut** [comment]
Further shadowsocks repos have been forked into my account. See the list above. Good luck and all the best from Berlin.

**Comment by mehulkar** [comment]
+1 to adding this in, but I don't think I have a good model for adding this category of events. Null Pointer Exception :stuck_out_tongue:. Any ideas?

**Comment by jomo** [comment]
How about this?

``` diff
+ - title: "Deleted, because of police"
+   link: "https://archive.is/r8k7X#30.1%"
+   type: "issue"
```

([link](https://archive.is/r8k7X#30.1%))

**Comment by mehulkar** [comment]
@jomo that works. want to make a PR?

**Comment by jomo** [comment]
Done! See #33.
