### ISSUE TITLE
published website is broken

### ISSUE THREAD

**Issue by mehulkar** [mehulkar/github-hall-of-fame#46]
because project was moved into a org with grand plans of other halls of fame outside of github. 

need to register a domain name and publish these there.

**Comment by jomo** [comment]
Well https://halls-of-fame.github.io/github/ works for now :)

**Comment by mehulkar** [comment]
oo, nice. maybe that's why i did it hah! 
registered `halls-of-fame.com` just now. will come back to this later. 

updating project description with the link
