### ISSUE TITLE
Consider merging with Github Drama

### ISSUE THREAD

**Issue by stevemoser** [mehulkar/github-hall-of-fame#49]
https://github.com/nikolas/github-drama

**Comment by mehulkar** [comment]
not opposed to it. although "drama" has a negative connotation and hall of fame has a positive connotation. I'd like to preserve the latter.

**Comment by mehulkar** [comment]
cc @nikolas

**Comment by vendethiel** [comment]
-1 for "drama" as well

**Comment by nikolas** [comment]
"Hall of Fame" has a positive connotation, and I'd like to preserve github-drama's negative connotation.

**Comment by mehulkar** [comment]
@nikolas  :) fair enough.
